cid = 2

jenis_kegiatan_options = {
    "5": "Co-Fasilitator P2K2 mulai dari persiapan hingga Welcoming Freshmen",
    "6": "Ketua Pengurus Organisasi Internal UIB",
    "7": "Anggota Pengurus Organisasi Internal UIB",
    "8": "Ketua Pengurus Organisasi Eksternal UIB (Internasional)",
    "9": "Anggota Pengurus Organisasi Eksternal UIB (Internasional)",
    "10": "Ketua Pengurus Organisasi Eksternal UIB (Nasional)",
    "11": "Anggota Pengurus Organisasi Eksternal UIB (Nasional)",
    "12": "Ketua Pengurus Organisasi Eksternal UIB (Wilayah/Provinsi)",
    "13": "Anggota Pengurus Organisasi Eksternal UIB (Wilayah/Provinsi)",
    "14": "Ketua Pengurus Organisasi Eksternal UIB (Lokal)",
    "15": "Anggota Pengurus Organisasi Eksternal UIB (Lokal)",
    "16": "Ketua Kepanitiaan Acara Internal UIB",
    "17": "Koordinator Kepanitiaan Acara Internal UIB",
    "18": "Pengisi Acara Kepanitiaan Acara Internal UIB",
    "19": "Anggota Kepanitiaan Acara Internal UIB",
    "20": "Ketua Kepanitiaan Acara Eksternal UIB (Internasional)",
    "21": "Koordinator Kepanitiaan Acara Eksternal UIB (Internasional)",
    "22": "Pengisi Acara Kepanitiaan Acara Eksternal UIB (Internasional)",
    "23": "Anggota Kepanitiaan Acara Eksternal UIB (Internasional)",
    "24": "Ketua Kepanitiaan Acara Eksternal UIB (Nasional)",
    "25": "Koordinator Kepanitiaan Acara Eksternal UIB (Nasional)",
    "26": "Pengisi Acara Kepanitiaan Acara Eksternal UIB (Nasional)",
    "27": "Anggota Kepanitiaan Acara Eksternal UIB (Nasional)",
    "28": "Ketua Kepanitiaan Acara Eksternal UIB (Wilayah/Provinsi)",
    "29": "Koordinator Kepanitiaan Acara Eksternal UIB (Wilayah/Provinsi)",
    "30": "Pengisi Acara Kepanitiaan Acara Eksternal UIB (Wilayah/Provinsi)",
    "31": "Anggota Kepanitiaan Acara Eksternal UIB (Wilayah/Provinsi)",
    "32": "Ketua Kepanitiaan Acara Eksternal UIB (Lokal)",
    "33": "Koordinator Kepanitiaan Acara Eksternal UIB (Lokal)",
    "34": "Pengisi Acara Kepanitiaan Acara Eksternal UIB (Lokal)",
    "35": "Anggota Kepanitiaan Acara Eksternal UIB (Lokal)"
}
