cid = 3

jenis_kegiatan_options = {
    "36": "Penghargaan Individu Internasional SKP Sesuai Bidang",
    "37": "Penghargaan Kelompok Internasional SKP Sesuai Bidang",
    "38": "Penghargaan Individu Internasional SKP Bidang Lainnya",
    "39": "Penghargaan Kelompok Internasional SKP Bidang Lainnya",
    "40": "Juara 1 Individu Internasional SKP Sesuai Bidang",
    "41": "Juara 1 Kelompok Internasional SKP Sesuai Bidang",
    "42": "Juara 1 Individu Internasional SKP Bidang Lainnya",
    "43": "Juara 1 Kelompok Internasional SKP Bidang Lainnya",
    "44": "Juara 2 Individu Internasional SKP Sesuai Bidang",
    "45": "Juara 2 Kelompok Internasional SKP Sesuai Bidang",
    "46": "Juara 2 Individu Internasional SKP Bidang Lainnya",
    "47": "Juara 2 Kelompok Internasional SKP Bidang Lainnya",
    "48": "Juara 3 Individu Internasional SKP Sesuai Bidang",
    "49": "Juara 3 Kelompok Internasional SKP Sesuai Bidang",
    "50": "Juara 3 Individu Internasional SKP Bidang Lainnya",
    "51": "Juara 3 Kelompok Internasional SKP Bidang Lainnya",
    "52": "Harapan Individu Internasional SKP Sesuai Bidang",
    "53": "Harapan Kelompok Internasional SKP Sesuai Bidang",
    "54": "Harapan Individu Internasional SKP Bidang Lainnya",
    "55": "Harapan Kelompok Internasional SKP Bidang Lainnya",
    "56": "Peserta Individu Internasional SKP Sesuai Bidang",
    "57": "Peserta Kelompok Internasional SKP Sesuai Bidang",
    "58": "Peserta Individu Internasional SKP Bidang Lainnya",
    "59": "Peserta Kelompok Internasional SKP Bidang Lainnya",
    "60": "Pelatih/Pendamping Individu Internasional SKP Sesuai Bidang",
    "61": "Pelatih/Pendamping Kelompok Internasional SKP Sesuai Bidang",
    "62": "Pelatih/Pendamping Individu Internasional SKP Bidang Lainnya",
    "63": "Pelatih/Pendamping Kelompok Internasional SKP Bidang Lainnya",
    "64": "Penghargaan Individu Nasional SKP Sesuai Bidang",
    "65": "Penghargaan Kelompok Nasional SKP Sesuai Bidang",
    "66": "Penghargaan Individu Nasional SKP Bidang Lainnya",
    "67": "Penghargaan Kelompok Nasional SKP Bidang Lainnya",
    "68": "Juara 1 Individu Nasional SKP Sesuai Bidang",
    "69": "Juara 1 Kelompok Nasional SKP Sesuai Bidang",
    "70": "Juara 1 Individu Nasional SKP Bidang Lainnya",
    "71": "Juara 1 Kelompok Nasional SKP Bidang Lainnya",
    "72": "Juara 2 Individu Nasional SKP Sesuai Bidang",
    "73": "Juara 2 Kelompok Nasional SKP Sesuai Bidang",
    "74": "Juara 2 Individu Nasional SKP Bidang Lainnya",
    "75": "Juara 2 Kelompok Nasional SKP Bidang Lainnya",
    "76": "Juara 3 Individu Nasional SKP Sesuai Bidang",
    "77": "Juara 3 Kelompok Nasional SKP Sesuai Bidang",
    "78": "Juara 3 Individu Nasional SKP Bidang Lainnya",
    "79": "Juara 3 Kelompok Nasional SKP Bidang Lainnya",
    "80": "Harapan Individu Nasional SKP Sesuai Bidang",
    "81": "Harapan Kelompok Nasional SKP Sesuai Bidang",
    "82": "Harapan Individu Nasional SKP Bidang Lainnya",
    "83": "Harapan Kelompok Nasional SKP Bidang Lainnya",
    "84": "Peserta Individu Nasional SKP Sesuai Bidang",
    "85": "Peserta Kelompok Nasional SKP Sesuai Bidang",
    "86": "Peserta Individu Nasional SKP Bidang Lainnya",
    "87": "Peserta Kelompok Nasional SKP Bidang Lainnya",
    "88": "Pelatih/Pendamping Individu Nasional SKP Sesuai Bidang",
    "89": "Pelatih/Pendamping Kelompok Nasional SKP Sesuai Bidang",
    "90": "Pelatih/Pendamping Individu Nasional SKP Bidang Lainnya",
    "91": "Pelatih/Pendamping Kelompok Nasional SKP Bidang Lainnya",
    "92": "Penghargaan Individu Provinsi SKP Sesuai Bidang",
    "93": "Penghargaan Kelompok Provinsi SKP Sesuai Bidang",
    "94": "Penghargaan Individu Provinsi SKP Bidang Lainnya",
    "95": "Penghargaan Kelompok Provinsi SKP Bidang Lainnya",
    "96": "Juara 1 Individu Provinsi SKP Sesuai Bidang",
    "97": "Juara 1 Kelompok Provinsi SKP Sesuai Bidang",
    "98": "Juara 1 Individu Provinsi SKP Bidang Lainnya",
    "99": "Juara 1 Kelompok Provinsi SKP Bidang Lainnya",
    "100": "Juara 2 Individu Provinsi SKP Sesuai Bidang",
    "101": "Juara 2 Kelompok Provinsi SKP Sesuai Bidang",
    "102": "Juara 2 Individu Provinsi SKP Bidang Lainnya",
    "103": "Juara 2 Kelompok Provinsi SKP Bidang Lainnya",
    "104": "Juara 3 Individu Provinsi SKP Sesuai Bidang",
    "105": "Juara 3 Kelompok Provinsi SKP Sesuai Bidang",
    "106": "Juara 3 Individu Provinsi SKP Bidang Lainnya",
    "107": "Juara 3 Kelompok Provinsi SKP Bidang Lainnya",
    "108": "Harapan Individu Provinsi SKP Sesuai Bidang",
    "109": "Harapan Kelompok Provinsi SKP Sesuai Bidang",
    "110": "Harapan Individu Provinsi SKP Bidang Lainnya",
    "111": "Harapan Kelompok Provinsi SKP Bidang Lainnya",
    "112": "Peserta Individu Provinsi SKP Sesuai Bidang",
    "113": "Peserta Kelompok Provinsi SKP Sesuai Bidang",
    "114": "Peserta Individu Provinsi SKP Bidang Lainnya",
    "115": "Peserta Kelompok Provinsi SKP Bidang Lainnya",
    "116": "Pelatih/Pendamping Individu Provinsi SKP Sesuai Bidang",
    "117": "Pelatih/Pendamping Kelompok Provinsi SKP Sesuai Bidang",
    "118": "Pelatih/Pendamping Individu Provinsi SKP Bidang Lainnya",
    "119": "Pelatih/Pendamping Kelompok Provinsi SKP Bidang Lainnya",
    "120": "Penghargaan Individu UIB/Lokal SKP Sesuai Bidang",
    "121": "Penghargaan Kelompok UIB/Lokal SKP Sesuai Bidang",
    "122": "Penghargaan Individu UIB/Lokal SKP Bidang Lainnya",
    "123": "Penghargaan Kelompok UIB/Lokal SKP Bidang Lainnya",
    "124": "Juara 1 Individu UIB/Lokal SKP Sesuai Bidang",
    "125": "Juara 1 Kelompok UIB/Lokal SKP Sesuai Bidang",
    "126": "Juara 1 Individu UIB/Lokal SKP Bidang Lainnya",
    "127": "Juara 1 Kelompok UIB/Lokal SKP Bidang Lainnya",
    "128": "Juara 2 Individu UIB/Lokal SKP Sesuai Bidang",
    "129": "Juara 2 Kelompok UIB/Lokal SKP Sesuai Bidang",
    "130": "Juara 2 Individu UIB/Lokal SKP Bidang Lainnya",
    "131": "Juara 2 Kelompok UIB/Lokal SKP Bidang Lainnya",
    "132": "Juara 3 Individu UIB/Lokal SKP Sesuai Bidang",
    "133": "Juara 3 Kelompok UIB/Lokal SKP Sesuai Bidang",
    "134": "Juara 3 Individu UIB/Lokal SKP Bidang Lainnya",
    "135": "Juara 3 Kelompok UIB/Lokal SKP Bidang Lainnya",
    "136": "Harapan Individu UIB/Lokal SKP Sesuai Bidang",
    "137": "Harapan Kelompok UIB/Lokal SKP Sesuai Bidang",
    "138": "Harapan Individu UIB/Lokal SKP Bidang Lainnya",
    "139": "Harapan Kelompok UIB/Lokal SKP Bidang Lainnya",
    "140": "Peserta Individu UIB/Lokal SKP Sesuai Bidang",
    "141": "Peserta Kelompok UIB/Lokal SKP Sesuai Bidang",
    "142": "Peserta Individu UIB/Lokal SKP Bidang Lainnya",
    "143": "Peserta Kelompok UIB/Lokal SKP Bidang Lainnya",
    "144": "Pelatih/Pendamping Individu UIB/Lokal SKP Sesuai Bidang",
    "145": "Pelatih/Pendamping Kelompok UIB/Lokal SKP Sesuai Bidang",
    "146": "Pelatih/Pendamping Individu UIB/Lokal SKP Bidang Lainnya",
    "147": "Pelatih/Pendamping Kelompok UIB/Lokal SKP Bidang Lainnya"
}

